USE [master]
GO

/****** Object:  Database [Asses]    Script Date: 23/11/2023 1:03:15 PM ******/
CREATE DATABASE [Asses]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Asses', FILENAME = N'D:\programs\Sql server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Asses.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Asses_log', FILENAME = N'D:\programs\Sql server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Asses_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Asses].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Asses] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Asses] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Asses] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Asses] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Asses] SET ARITHABORT OFF 
GO

ALTER DATABASE [Asses] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Asses] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Asses] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Asses] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Asses] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Asses] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Asses] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Asses] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Asses] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Asses] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Asses] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Asses] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Asses] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Asses] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Asses] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Asses] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Asses] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Asses] SET RECOVERY FULL 
GO

ALTER DATABASE [Asses] SET  MULTI_USER 
GO

ALTER DATABASE [Asses] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Asses] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Asses] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Asses] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Asses] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Asses] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Asses] SET QUERY_STORE = ON
GO

ALTER DATABASE [Asses] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Asses] SET  READ_WRITE 
GO

